#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Base_de_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBIncidencias")]
	public partial class BDIncidenciasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAreas(Areas instance);
    partial void UpdateAreas(Areas instance);
    partial void DeleteAreas(Areas instance);
    partial void InsertAuditoria(Auditoria instance);
    partial void UpdateAuditoria(Auditoria instance);
    partial void DeleteAuditoria(Auditoria instance);
    partial void InsertEstados(Estados instance);
    partial void UpdateEstados(Estados instance);
    partial void DeleteEstados(Estados instance);
    partial void InsertGuias(Guias instance);
    partial void UpdateGuias(Guias instance);
    partial void DeleteGuias(Guias instance);
    partial void InsertIncidencias(Incidencias instance);
    partial void UpdateIncidencias(Incidencias instance);
    partial void DeleteIncidencias(Incidencias instance);
    partial void InsertPrioridades(Prioridades instance);
    partial void UpdatePrioridades(Prioridades instance);
    partial void DeletePrioridades(Prioridades instance);
    partial void InsertReportesMensualesEnviados(ReportesMensualesEnviados instance);
    partial void UpdateReportesMensualesEnviados(ReportesMensualesEnviados instance);
    partial void DeleteReportesMensualesEnviados(ReportesMensualesEnviados instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public BDIncidenciasDataContext() : 
				base(global::Datos.Properties.Settings.Default.DBIncidenciasConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public BDIncidenciasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDIncidenciasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDIncidenciasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDIncidenciasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Areas> Areas
		{
			get
			{
				return this.GetTable<Areas>();
			}
		}
		
		public System.Data.Linq.Table<Auditoria> Auditoria
		{
			get
			{
				return this.GetTable<Auditoria>();
			}
		}
		
		public System.Data.Linq.Table<Estados> Estados
		{
			get
			{
				return this.GetTable<Estados>();
			}
		}
		
		public System.Data.Linq.Table<Guias> Guias
		{
			get
			{
				return this.GetTable<Guias>();
			}
		}
		
		public System.Data.Linq.Table<Incidencias> Incidencias
		{
			get
			{
				return this.GetTable<Incidencias>();
			}
		}
		
		public System.Data.Linq.Table<Prioridades> Prioridades
		{
			get
			{
				return this.GetTable<Prioridades>();
			}
		}
		
		public System.Data.Linq.Table<ReportesMensualesEnviados> ReportesMensualesEnviados
		{
			get
			{
				return this.GetTable<ReportesMensualesEnviados>();
			}
		}
		
		public System.Data.Linq.Table<TelegramMensajes> TelegramMensajes
		{
			get
			{
				return this.GetTable<TelegramMensajes>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Areas_Eliminar")]
		public int sp_Areas_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArea", DbType="Int")] System.Nullable<int> idArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArea);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Areas_Insertar")]
		public int sp_Areas_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreArea", DbType="VarChar(100)")] string nombreArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreArea);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Areas_Listar")]
		public ISingleResult<sp_Areas_ListarResult> sp_Areas_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Areas_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Areas_Modificar")]
		public int sp_Areas_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArea", DbType="Int")] System.Nullable<int> idArea, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreArea", DbType="VarChar(100)")] string nombreArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArea, nombreArea);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Auditoria_Insertar")]
		public int sp_Auditoria_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(150)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(50)")] string accion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Entidad", DbType="VarChar(50)")] string entidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntidadId", DbType="Int")] System.Nullable<int> entidadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Detalle", DbType="VarChar(MAX)")] string detalle)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombreUsuario, accion, entidad, entidadId, detalle);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Auditoria_Listar")]
		public ISingleResult<sp_Auditoria_ListarResult> sp_Auditoria_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Auditoria_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Estados_Eliminar")]
		public int sp_Estados_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEstado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Estados_Insertar")]
		public int sp_Estados_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Estados_Listar")]
		public ISingleResult<sp_Estados_ListarResult> sp_Estados_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Estados_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Estados_Modificar")]
		public int sp_Estados_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEstado, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Guias_Eliminar")]
		public int sp_Guias_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGuia", DbType="Int")] System.Nullable<int> idGuia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGuia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Guias_Insertar")]
		public int sp_Guias_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(150)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Problema", DbType="VarChar(MAX)")] string problema, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Solucion", DbType="VarChar(MAX)")] string solucion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, problema, solucion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Guias_Listar")]
		public ISingleResult<sp_Guias_ListarResult> sp_Guias_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Guias_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Guias_Modificar")]
		public int sp_Guias_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGuia", DbType="Int")] System.Nullable<int> idGuia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(150)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Problema", DbType="VarChar(MAX)")] string problema, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Solucion", DbType="VarChar(MAX)")] string solucion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGuia, titulo, problema, solucion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_ActualizarEstadoTelegram")]
		public int sp_Incidencias_ActualizarEstadoTelegram([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdIncidencia", DbType="Int")] System.Nullable<int> idIncidencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTecnico", DbType="Int")] System.Nullable<int> idTecnico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNuevoEstado", DbType="Int")] System.Nullable<int> idNuevoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(MAX)")] string observaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idIncidencia, idTecnico, idNuevoEstado, observaciones, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_AsignarTecnicoTelegram")]
		public int sp_Incidencias_AsignarTecnicoTelegram([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdIncidencia", DbType="Int")] System.Nullable<int> idIncidencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTecnico", DbType="Int")] System.Nullable<int> idTecnico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstadoEnProceso", DbType="Int")] System.Nullable<int> idEstadoEnProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idIncidencia, idTecnico, idEstadoEnProceso, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_Eliminar")]
		public int sp_Incidencias_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdIncidencia", DbType="Int")] System.Nullable<int> idIncidencia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idIncidencia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_Insertar")]
		public int sp_Incidencias_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Empleado", DbType="VarChar(150)")] string empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArea", DbType="Int")] System.Nullable<int> idArea, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoIncidencia", DbType="VarChar(100)")] string tipoIncidencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPrioridad", DbType="Int")] System.Nullable<int> idPrioridad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTecnicoAsignado", DbType="Int")] System.Nullable<int> idTecnicoAsignado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(MAX)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empleado, idArea, tipoIncidencia, descripcion, idPrioridad, idEstado, idTecnicoAsignado, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Prioridades_Eliminar")]
		public int sp_Prioridades_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPrioridad", DbType="Int")] System.Nullable<int> idPrioridad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPrioridad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Prioridades_Insertar")]
		public int sp_Prioridades_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Prioridades_Listar")]
		public ISingleResult<sp_Prioridades_ListarResult> sp_Prioridades_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Prioridades_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Prioridades_Modificar")]
		public int sp_Prioridades_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPrioridad", DbType="Int")] System.Nullable<int> idPrioridad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPrioridad, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_Eliminar")]
		public int sp_Usuarios_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_Insertar")]
		public int sp_Usuarios_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(100)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(150)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="VarChar(50)")] string rol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, correo, usuario, password, rol, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_Listar")]
		public ISingleResult<sp_Usuarios_ListarResult> sp_Usuarios_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Usuarios_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_Login")]
		public ISingleResult<sp_Usuarios_LoginResult> sp_Usuarios_Login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario);
			return ((ISingleResult<sp_Usuarios_LoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_Modificar")]
		public int sp_Usuarios_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(100)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(150)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="VarChar(50)")] string rol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelegramChatId", DbType="BigInt")] System.Nullable<long> telegramChatId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FotoPerfil", DbType="VarBinary(MAX)")] System.Data.Linq.Binary fotoPerfil)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombre, apellido, correo, usuario, password, rol, estado, telegramChatId, fotoPerfil);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_RegistrarIntentoFallido")]
		public int sp_Usuarios_RegistrarIntentoFallido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Usuarios_ResetearIntentos")]
		public int sp_Usuarios_ResetearIntentos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_Listar")]
		public ISingleResult<sp_Incidencias_ListarResult> sp_Incidencias_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Incidencias_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Incidencias_Modificar")]
		public int sp_Incidencias_Modificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdIncidencia", DbType="Int")] System.Nullable<int> idIncidencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Empleado", DbType="VarChar(150)")] string empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArea", DbType="Int")] System.Nullable<int> idArea, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoIncidencia", DbType="VarChar(100)")] string tipoIncidencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPrioridad", DbType="Int")] System.Nullable<int> idPrioridad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTecnicoAsignado", DbType="Int")] System.Nullable<int> idTecnicoAsignado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaSolucion", DbType="DateTime")] System.Nullable<System.DateTime> fechaSolucion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(MAX)")] string observaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FilaVersionOriginal", DbType="Binary(8)")] System.Data.Linq.Binary filaVersionOriginal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idIncidencia, empleado, idArea, tipoIncidencia, descripcion, idPrioridad, idEstado, idTecnicoAsignado, fechaSolucion, observaciones, filaVersionOriginal);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Areas")]
	public partial class Areas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdArea;
		
		private string _NombreArea;
		
		private EntitySet<Incidencias> _Incidencias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAreaChanging(int value);
    partial void OnIdAreaChanged();
    partial void OnNombreAreaChanging(string value);
    partial void OnNombreAreaChanged();
    #endregion
		
		public Areas()
		{
			this._Incidencias = new EntitySet<Incidencias>(new Action<Incidencias>(this.attach_Incidencias), new Action<Incidencias>(this.detach_Incidencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArea", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreArea
		{
			get
			{
				return this._NombreArea;
			}
			set
			{
				if ((this._NombreArea != value))
				{
					this.OnNombreAreaChanging(value);
					this.SendPropertyChanging();
					this._NombreArea = value;
					this.SendPropertyChanged("NombreArea");
					this.OnNombreAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Areas_Incidencias", Storage="_Incidencias", ThisKey="IdArea", OtherKey="IdArea")]
		public EntitySet<Incidencias> Incidencias
		{
			get
			{
				return this._Incidencias;
			}
			set
			{
				this._Incidencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Areas = this;
		}
		
		private void detach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Areas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auditoria")]
	public partial class Auditoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAuditoria;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<int> _IdUsuario;
		
		private string _NombreUsuario;
		
		private string _Accion;
		
		private string _Entidad;
		
		private System.Nullable<int> _EntidadId;
		
		private string _Detalle;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAuditoriaChanging(int value);
    partial void OnIdAuditoriaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnAccionChanging(string value);
    partial void OnAccionChanged();
    partial void OnEntidadChanging(string value);
    partial void OnEntidadChanged();
    partial void OnEntidadIdChanging(System.Nullable<int> value);
    partial void OnEntidadIdChanged();
    partial void OnDetalleChanging(string value);
    partial void OnDetalleChanged();
    #endregion
		
		public Auditoria()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAuditoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAuditoria
		{
			get
			{
				return this._IdAuditoria;
			}
			set
			{
				if ((this._IdAuditoria != value))
				{
					this.OnIdAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._IdAuditoria = value;
					this.SendPropertyChanged("IdAuditoria");
					this.OnIdAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this.OnAccionChanging(value);
					this.SendPropertyChanging();
					this._Accion = value;
					this.SendPropertyChanged("Accion");
					this.OnAccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Entidad
		{
			get
			{
				return this._Entidad;
			}
			set
			{
				if ((this._Entidad != value))
				{
					this.OnEntidadChanging(value);
					this.SendPropertyChanging();
					this._Entidad = value;
					this.SendPropertyChanged("Entidad");
					this.OnEntidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadId", DbType="Int")]
		public System.Nullable<int> EntidadId
		{
			get
			{
				return this._EntidadId;
			}
			set
			{
				if ((this._EntidadId != value))
				{
					this.OnEntidadIdChanging(value);
					this.SendPropertyChanging();
					this._EntidadId = value;
					this.SendPropertyChanged("EntidadId");
					this.OnEntidadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="VarChar(MAX)")]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Auditoria", Storage="_Usuarios", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Auditoria.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Auditoria.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estados")]
	public partial class Estados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstado;
		
		private string _Nombre;
		
		private EntitySet<Incidencias> _Incidencias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoChanging(int value);
    partial void OnIdEstadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Estados()
		{
			this._Incidencias = new EntitySet<Incidencias>(new Action<Incidencias>(this.attach_Incidencias), new Action<Incidencias>(this.detach_Incidencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Incidencias", Storage="_Incidencias", ThisKey="IdEstado", OtherKey="IdEstado")]
		public EntitySet<Incidencias> Incidencias
		{
			get
			{
				return this._Incidencias;
			}
			set
			{
				this._Incidencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Estados = this;
		}
		
		private void detach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Estados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guias")]
	public partial class Guias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGuia;
		
		private string _Titulo;
		
		private string _Problema;
		
		private string _Solucion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGuiaChanging(int value);
    partial void OnIdGuiaChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnProblemaChanging(string value);
    partial void OnProblemaChanged();
    partial void OnSolucionChanging(string value);
    partial void OnSolucionChanged();
    #endregion
		
		public Guias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGuia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdGuia
		{
			get
			{
				return this._IdGuia;
			}
			set
			{
				if ((this._IdGuia != value))
				{
					this.OnIdGuiaChanging(value);
					this.SendPropertyChanging();
					this._IdGuia = value;
					this.SendPropertyChanged("IdGuia");
					this.OnIdGuiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Problema", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Problema
		{
			get
			{
				return this._Problema;
			}
			set
			{
				if ((this._Problema != value))
				{
					this.OnProblemaChanging(value);
					this.SendPropertyChanging();
					this._Problema = value;
					this.SendPropertyChanged("Problema");
					this.OnProblemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solucion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Solucion
		{
			get
			{
				return this._Solucion;
			}
			set
			{
				if ((this._Solucion != value))
				{
					this.OnSolucionChanging(value);
					this.SendPropertyChanging();
					this._Solucion = value;
					this.SendPropertyChanged("Solucion");
					this.OnSolucionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Incidencias")]
	public partial class Incidencias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdIncidencia;
		
		private System.DateTime _Fecha;
		
		private string _Empleado;
		
		private int _IdArea;
		
		private string _TipoIncidencia;
		
		private string _Descripcion;
		
		private int _IdPrioridad;
		
		private int _IdEstado;
		
		private System.Nullable<int> _IdTecnicoAsignado;
		
		private System.Nullable<System.DateTime> _FechaSolucion;
		
		private string _Observaciones;
		
		private string _NumeroTicket;
		
		private bool _EscaladoSLA;
		
		private System.Data.Linq.Binary _FilaVersion;
		
		private EntityRef<Areas> _Areas;
		
		private EntityRef<Estados> _Estados;
		
		private EntityRef<Prioridades> _Prioridades;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdIncidenciaChanging(int value);
    partial void OnIdIncidenciaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnEmpleadoChanging(string value);
    partial void OnEmpleadoChanged();
    partial void OnIdAreaChanging(int value);
    partial void OnIdAreaChanged();
    partial void OnTipoIncidenciaChanging(string value);
    partial void OnTipoIncidenciaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnIdPrioridadChanging(int value);
    partial void OnIdPrioridadChanged();
    partial void OnIdEstadoChanging(int value);
    partial void OnIdEstadoChanged();
    partial void OnIdTecnicoAsignadoChanging(System.Nullable<int> value);
    partial void OnIdTecnicoAsignadoChanged();
    partial void OnFechaSolucionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaSolucionChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnNumeroTicketChanging(string value);
    partial void OnNumeroTicketChanged();
    partial void OnEscaladoSLAChanging(bool value);
    partial void OnEscaladoSLAChanged();
    partial void OnFilaVersionChanging(System.Data.Linq.Binary value);
    partial void OnFilaVersionChanged();
    #endregion
		
		public Incidencias()
		{
			this._Areas = default(EntityRef<Areas>);
			this._Estados = default(EntityRef<Estados>);
			this._Prioridades = default(EntityRef<Prioridades>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdIncidencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int IdIncidencia
		{
			get
			{
				return this._IdIncidencia;
			}
			set
			{
				if ((this._IdIncidencia != value))
				{
					this.OnIdIncidenciaChanging(value);
					this.SendPropertyChanging();
					this._IdIncidencia = value;
					this.SendPropertyChanged("IdIncidencia");
					this.OnIdIncidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado", DbType="VarChar(150) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				if ((this._Empleado != value))
				{
					this.OnEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._Empleado = value;
					this.SendPropertyChanged("Empleado");
					this.OnEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					if (this._Areas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIncidencia", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TipoIncidencia
		{
			get
			{
				return this._TipoIncidencia;
			}
			set
			{
				if ((this._TipoIncidencia != value))
				{
					this.OnTipoIncidenciaChanging(value);
					this.SendPropertyChanging();
					this._TipoIncidencia = value;
					this.SendPropertyChanged("TipoIncidencia");
					this.OnTipoIncidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPrioridad", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int IdPrioridad
		{
			get
			{
				return this._IdPrioridad;
			}
			set
			{
				if ((this._IdPrioridad != value))
				{
					if (this._Prioridades.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPrioridadChanging(value);
					this.SendPropertyChanging();
					this._IdPrioridad = value;
					this.SendPropertyChanged("IdPrioridad");
					this.OnIdPrioridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					if (this._Estados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTecnicoAsignado", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IdTecnicoAsignado
		{
			get
			{
				return this._IdTecnicoAsignado;
			}
			set
			{
				if ((this._IdTecnicoAsignado != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTecnicoAsignadoChanging(value);
					this.SendPropertyChanging();
					this._IdTecnicoAsignado = value;
					this.SendPropertyChanged("IdTecnicoAsignado");
					this.OnIdTecnicoAsignadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolucion", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> FechaSolucion
		{
			get
			{
				return this._FechaSolucion;
			}
			set
			{
				if ((this._FechaSolucion != value))
				{
					this.OnFechaSolucionChanging(value);
					this.SendPropertyChanging();
					this._FechaSolucion = value;
					this.SendPropertyChanged("FechaSolucion");
					this.OnFechaSolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTicket", AutoSync=AutoSync.Always, DbType="VarChar(15)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string NumeroTicket
		{
			get
			{
				return this._NumeroTicket;
			}
			set
			{
				if ((this._NumeroTicket != value))
				{
					this.OnNumeroTicketChanging(value);
					this.SendPropertyChanging();
					this._NumeroTicket = value;
					this.SendPropertyChanged("NumeroTicket");
					this.OnNumeroTicketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EscaladoSLA", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool EscaladoSLA
		{
			get
			{
				return this._EscaladoSLA;
			}
			set
			{
				if ((this._EscaladoSLA != value))
				{
					this.OnEscaladoSLAChanging(value);
					this.SendPropertyChanging();
					this._EscaladoSLA = value;
					this.SendPropertyChanged("EscaladoSLA");
					this.OnEscaladoSLAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilaVersion", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FilaVersion
		{
			get
			{
				return this._FilaVersion;
			}
			set
			{
				if ((this._FilaVersion != value))
				{
					this.OnFilaVersionChanging(value);
					this.SendPropertyChanging();
					this._FilaVersion = value;
					this.SendPropertyChanged("FilaVersion");
					this.OnFilaVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Areas_Incidencias", Storage="_Areas", ThisKey="IdArea", OtherKey="IdArea", IsForeignKey=true)]
		public Areas Areas
		{
			get
			{
				return this._Areas.Entity;
			}
			set
			{
				Areas previousValue = this._Areas.Entity;
				if (((previousValue != value) 
							|| (this._Areas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Areas.Entity = null;
						previousValue.Incidencias.Remove(this);
					}
					this._Areas.Entity = value;
					if ((value != null))
					{
						value.Incidencias.Add(this);
						this._IdArea = value.IdArea;
					}
					else
					{
						this._IdArea = default(int);
					}
					this.SendPropertyChanged("Areas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Incidencias", Storage="_Estados", ThisKey="IdEstado", OtherKey="IdEstado", IsForeignKey=true)]
		public Estados Estados
		{
			get
			{
				return this._Estados.Entity;
			}
			set
			{
				Estados previousValue = this._Estados.Entity;
				if (((previousValue != value) 
							|| (this._Estados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estados.Entity = null;
						previousValue.Incidencias.Remove(this);
					}
					this._Estados.Entity = value;
					if ((value != null))
					{
						value.Incidencias.Add(this);
						this._IdEstado = value.IdEstado;
					}
					else
					{
						this._IdEstado = default(int);
					}
					this.SendPropertyChanged("Estados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prioridades_Incidencias", Storage="_Prioridades", ThisKey="IdPrioridad", OtherKey="IdPrioridad", IsForeignKey=true)]
		public Prioridades Prioridades
		{
			get
			{
				return this._Prioridades.Entity;
			}
			set
			{
				Prioridades previousValue = this._Prioridades.Entity;
				if (((previousValue != value) 
							|| (this._Prioridades.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prioridades.Entity = null;
						previousValue.Incidencias.Remove(this);
					}
					this._Prioridades.Entity = value;
					if ((value != null))
					{
						value.Incidencias.Add(this);
						this._IdPrioridad = value.IdPrioridad;
					}
					else
					{
						this._IdPrioridad = default(int);
					}
					this.SendPropertyChanged("Prioridades");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Incidencias", Storage="_Usuarios", ThisKey="IdTecnicoAsignado", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Incidencias.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Incidencias.Add(this);
						this._IdTecnicoAsignado = value.IdUsuario;
					}
					else
					{
						this._IdTecnicoAsignado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prioridades")]
	public partial class Prioridades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPrioridad;
		
		private string _Nombre;
		
		private EntitySet<Incidencias> _Incidencias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPrioridadChanging(int value);
    partial void OnIdPrioridadChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Prioridades()
		{
			this._Incidencias = new EntitySet<Incidencias>(new Action<Incidencias>(this.attach_Incidencias), new Action<Incidencias>(this.detach_Incidencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPrioridad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPrioridad
		{
			get
			{
				return this._IdPrioridad;
			}
			set
			{
				if ((this._IdPrioridad != value))
				{
					this.OnIdPrioridadChanging(value);
					this.SendPropertyChanging();
					this._IdPrioridad = value;
					this.SendPropertyChanged("IdPrioridad");
					this.OnIdPrioridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prioridades_Incidencias", Storage="_Incidencias", ThisKey="IdPrioridad", OtherKey="IdPrioridad")]
		public EntitySet<Incidencias> Incidencias
		{
			get
			{
				return this._Incidencias;
			}
			set
			{
				this._Incidencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Prioridades = this;
		}
		
		private void detach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Prioridades = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportesMensualesEnviados")]
	public partial class ReportesMensualesEnviados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReporte;
		
		private int _Anio;
		
		private int _Mes;
		
		private System.DateTime _FechaEnvio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdReporteChanging(int value);
    partial void OnIdReporteChanged();
    partial void OnAnioChanging(int value);
    partial void OnAnioChanged();
    partial void OnMesChanging(int value);
    partial void OnMesChanged();
    partial void OnFechaEnvioChanging(System.DateTime value);
    partial void OnFechaEnvioChanged();
    #endregion
		
		public ReportesMensualesEnviados()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReporte", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdReporte
		{
			get
			{
				return this._IdReporte;
			}
			set
			{
				if ((this._IdReporte != value))
				{
					this.OnIdReporteChanging(value);
					this.SendPropertyChanging();
					this._IdReporte = value;
					this.SendPropertyChanged("IdReporte");
					this.OnIdReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anio", DbType="Int NOT NULL")]
		public int Anio
		{
			get
			{
				return this._Anio;
			}
			set
			{
				if ((this._Anio != value))
				{
					this.OnAnioChanging(value);
					this.SendPropertyChanging();
					this._Anio = value;
					this.SendPropertyChanged("Anio");
					this.OnAnioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="Int NOT NULL")]
		public int Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this.OnMesChanging(value);
					this.SendPropertyChanging();
					this._Mes = value;
					this.SendPropertyChanged("Mes");
					this.OnMesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this.OnFechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaEnvio = value;
					this.SendPropertyChanged("FechaEnvio");
					this.OnFechaEnvioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TelegramMensajes")]
	public partial class TelegramMensajes
	{
		
		private int _IdIncidencia;
		
		private long _ChatId;
		
		private int _MessageId;
		
		public TelegramMensajes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdIncidencia", DbType="Int NOT NULL")]
		public int IdIncidencia
		{
			get
			{
				return this._IdIncidencia;
			}
			set
			{
				if ((this._IdIncidencia != value))
				{
					this._IdIncidencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatId", DbType="BigInt NOT NULL")]
		public long ChatId
		{
			get
			{
				return this._ChatId;
			}
			set
			{
				if ((this._ChatId != value))
				{
					this._ChatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", DbType="Int NOT NULL")]
		public int MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if ((this._MessageId != value))
				{
					this._MessageId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Usuario;
		
		private string _Password;
		
		private string _Rol;
		
		private bool _Estado;
		
		private System.Nullable<long> _TelegramChatId;
		
		private int _IntentosFallidos;
		
		private System.Nullable<System.DateTime> _BloqueadoHasta;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		private EntitySet<Auditoria> _Auditoria;
		
		private EntitySet<Incidencias> _Incidencias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    partial void OnTelegramChatIdChanging(System.Nullable<long> value);
    partial void OnTelegramChatIdChanged();
    partial void OnIntentosFallidosChanging(int value);
    partial void OnIntentosFallidosChanged();
    partial void OnBloqueadoHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnBloqueadoHastaChanged();
    partial void OnFotoPerfilChanging(System.Data.Linq.Binary value);
    partial void OnFotoPerfilChanged();
    #endregion
		
		public Usuarios()
		{
			this._Auditoria = new EntitySet<Auditoria>(new Action<Auditoria>(this.attach_Auditoria), new Action<Auditoria>(this.detach_Auditoria));
			this._Incidencias = new EntitySet<Incidencias>(new Action<Incidencias>(this.attach_Incidencias), new Action<Incidencias>(this.detach_Incidencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelegramChatId", DbType="BigInt")]
		public System.Nullable<long> TelegramChatId
		{
			get
			{
				return this._TelegramChatId;
			}
			set
			{
				if ((this._TelegramChatId != value))
				{
					this.OnTelegramChatIdChanging(value);
					this.SendPropertyChanging();
					this._TelegramChatId = value;
					this.SendPropertyChanged("TelegramChatId");
					this.OnTelegramChatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentosFallidos", DbType="Int NOT NULL")]
		public int IntentosFallidos
		{
			get
			{
				return this._IntentosFallidos;
			}
			set
			{
				if ((this._IntentosFallidos != value))
				{
					this.OnIntentosFallidosChanging(value);
					this.SendPropertyChanging();
					this._IntentosFallidos = value;
					this.SendPropertyChanged("IntentosFallidos");
					this.OnIntentosFallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqueadoHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> BloqueadoHasta
		{
			get
			{
				return this._BloqueadoHasta;
			}
			set
			{
				if ((this._BloqueadoHasta != value))
				{
					this.OnBloqueadoHastaChanging(value);
					this.SendPropertyChanging();
					this._BloqueadoHasta = value;
					this.SendPropertyChanged("BloqueadoHasta");
					this.OnBloqueadoHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this.OnFotoPerfilChanging(value);
					this.SendPropertyChanging();
					this._FotoPerfil = value;
					this.SendPropertyChanged("FotoPerfil");
					this.OnFotoPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Auditoria", Storage="_Auditoria", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<Auditoria> Auditoria
		{
			get
			{
				return this._Auditoria;
			}
			set
			{
				this._Auditoria.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Incidencias", Storage="_Incidencias", ThisKey="IdUsuario", OtherKey="IdTecnicoAsignado")]
		public EntitySet<Incidencias> Incidencias
		{
			get
			{
				return this._Incidencias;
			}
			set
			{
				this._Incidencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Auditoria(Auditoria entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Auditoria(Auditoria entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Incidencias(Incidencias entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	public partial class sp_Areas_ListarResult
	{
		
		private int _IdArea;
		
		private string _NombreArea;
		
		public sp_Areas_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int NOT NULL")]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this._IdArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArea", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreArea
		{
			get
			{
				return this._NombreArea;
			}
			set
			{
				if ((this._NombreArea != value))
				{
					this._NombreArea = value;
				}
			}
		}
	}
	
	public partial class sp_Auditoria_ListarResult
	{
		
		private int _IdAuditoria;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<int> _IdUsuario;
		
		private string _NombreUsuario;
		
		private string _Accion;
		
		private string _Entidad;
		
		private System.Nullable<int> _EntidadId;
		
		private string _Detalle;
		
		public sp_Auditoria_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAuditoria", DbType="Int NOT NULL")]
		public int IdAuditoria
		{
			get
			{
				return this._IdAuditoria;
			}
			set
			{
				if ((this._IdAuditoria != value))
				{
					this._IdAuditoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this._Accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Entidad
		{
			get
			{
				return this._Entidad;
			}
			set
			{
				if ((this._Entidad != value))
				{
					this._Entidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadId", DbType="Int")]
		public System.Nullable<int> EntidadId
		{
			get
			{
				return this._EntidadId;
			}
			set
			{
				if ((this._EntidadId != value))
				{
					this._EntidadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="VarChar(MAX)")]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this._Detalle = value;
				}
			}
		}
	}
	
	public partial class sp_Estados_ListarResult
	{
		
		private int _IdEstado;
		
		private string _Nombre;
		
		public sp_Estados_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class sp_Guias_ListarResult
	{
		
		private int _IdGuia;
		
		private string _Titulo;
		
		private string _Problema;
		
		private string _Solucion;
		
		public sp_Guias_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGuia", DbType="Int NOT NULL")]
		public int IdGuia
		{
			get
			{
				return this._IdGuia;
			}
			set
			{
				if ((this._IdGuia != value))
				{
					this._IdGuia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Problema", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Problema
		{
			get
			{
				return this._Problema;
			}
			set
			{
				if ((this._Problema != value))
				{
					this._Problema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solucion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Solucion
		{
			get
			{
				return this._Solucion;
			}
			set
			{
				if ((this._Solucion != value))
				{
					this._Solucion = value;
				}
			}
		}
	}
	
	public partial class sp_Prioridades_ListarResult
	{
		
		private int _IdPrioridad;
		
		private string _Nombre;
		
		public sp_Prioridades_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPrioridad", DbType="Int NOT NULL")]
		public int IdPrioridad
		{
			get
			{
				return this._IdPrioridad;
			}
			set
			{
				if ((this._IdPrioridad != value))
				{
					this._IdPrioridad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class sp_Usuarios_ListarResult
	{
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Usuario;
		
		private string _Password;
		
		private string _Rol;
		
		private bool _Estado;
		
		private System.Nullable<long> _TelegramChatId;
		
		private int _IntentosFallidos;
		
		private System.Nullable<System.DateTime> _BloqueadoHasta;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		public sp_Usuarios_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelegramChatId", DbType="BigInt")]
		public System.Nullable<long> TelegramChatId
		{
			get
			{
				return this._TelegramChatId;
			}
			set
			{
				if ((this._TelegramChatId != value))
				{
					this._TelegramChatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentosFallidos", DbType="Int NOT NULL")]
		public int IntentosFallidos
		{
			get
			{
				return this._IntentosFallidos;
			}
			set
			{
				if ((this._IntentosFallidos != value))
				{
					this._IntentosFallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqueadoHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> BloqueadoHasta
		{
			get
			{
				return this._BloqueadoHasta;
			}
			set
			{
				if ((this._BloqueadoHasta != value))
				{
					this._BloqueadoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this._FotoPerfil = value;
				}
			}
		}
	}
	
	public partial class sp_Usuarios_LoginResult
	{
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Usuario;
		
		private string _Password;
		
		private string _Rol;
		
		private bool _Estado;
		
		private System.Nullable<long> _TelegramChatId;
		
		private int _IntentosFallidos;
		
		private System.Nullable<System.DateTime> _BloqueadoHasta;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		public sp_Usuarios_LoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelegramChatId", DbType="BigInt")]
		public System.Nullable<long> TelegramChatId
		{
			get
			{
				return this._TelegramChatId;
			}
			set
			{
				if ((this._TelegramChatId != value))
				{
					this._TelegramChatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentosFallidos", DbType="Int NOT NULL")]
		public int IntentosFallidos
		{
			get
			{
				return this._IntentosFallidos;
			}
			set
			{
				if ((this._IntentosFallidos != value))
				{
					this._IntentosFallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqueadoHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> BloqueadoHasta
		{
			get
			{
				return this._BloqueadoHasta;
			}
			set
			{
				if ((this._BloqueadoHasta != value))
				{
					this._BloqueadoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this._FotoPerfil = value;
				}
			}
		}
	}
	
	public partial class sp_Incidencias_ListarResult
	{
		
		private int _IdIncidencia;
		
		private string _NumeroTicket;
		
		private System.DateTime _Fecha;
		
		private string _Empleado;
		
		private int _IdArea;
		
		private string _NombreArea;
		
		private string _TipoIncidencia;
		
		private string _Descripcion;
		
		private int _IdPrioridad;
		
		private string _NombrePrioridad;
		
		private int _IdEstado;
		
		private string _NombreEstado;
		
		private System.Nullable<int> _IdTecnicoAsignado;
		
		private string _TecnicoAsignado;
		
		private System.Nullable<System.DateTime> _FechaSolucion;
		
		private string _Observaciones;
		
		private System.Data.Linq.Binary _FilaVersion;
		
		public sp_Incidencias_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdIncidencia", DbType="Int NOT NULL")]
		public int IdIncidencia
		{
			get
			{
				return this._IdIncidencia;
			}
			set
			{
				if ((this._IdIncidencia != value))
				{
					this._IdIncidencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTicket", DbType="VarChar(15)")]
		public string NumeroTicket
		{
			get
			{
				return this._NumeroTicket;
			}
			set
			{
				if ((this._NumeroTicket != value))
				{
					this._NumeroTicket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				if ((this._Empleado != value))
				{
					this._Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int NOT NULL")]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this._IdArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArea", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreArea
		{
			get
			{
				return this._NombreArea;
			}
			set
			{
				if ((this._NombreArea != value))
				{
					this._NombreArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIncidencia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TipoIncidencia
		{
			get
			{
				return this._TipoIncidencia;
			}
			set
			{
				if ((this._TipoIncidencia != value))
				{
					this._TipoIncidencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPrioridad", DbType="Int NOT NULL")]
		public int IdPrioridad
		{
			get
			{
				return this._IdPrioridad;
			}
			set
			{
				if ((this._IdPrioridad != value))
				{
					this._IdPrioridad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePrioridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombrePrioridad
		{
			get
			{
				return this._NombrePrioridad;
			}
			set
			{
				if ((this._NombrePrioridad != value))
				{
					this._NombrePrioridad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEstado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreEstado
		{
			get
			{
				return this._NombreEstado;
			}
			set
			{
				if ((this._NombreEstado != value))
				{
					this._NombreEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTecnicoAsignado", DbType="Int")]
		public System.Nullable<int> IdTecnicoAsignado
		{
			get
			{
				return this._IdTecnicoAsignado;
			}
			set
			{
				if ((this._IdTecnicoAsignado != value))
				{
					this._IdTecnicoAsignado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TecnicoAsignado", DbType="VarChar(201)")]
		public string TecnicoAsignado
		{
			get
			{
				return this._TecnicoAsignado;
			}
			set
			{
				if ((this._TecnicoAsignado != value))
				{
					this._TecnicoAsignado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSolucion
		{
			get
			{
				return this._FechaSolucion;
			}
			set
			{
				if ((this._FechaSolucion != value))
				{
					this._FechaSolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(MAX)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this._Observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilaVersion", DbType="rowversion NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary FilaVersion
		{
			get
			{
				return this._FilaVersion;
			}
			set
			{
				if ((this._FilaVersion != value))
				{
					this._FilaVersion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
